### ISSUE TITLE
[BUG] /mnt/dev fails to unmount, blocking install (`arch-chroot`/`pacstrap` issue, I assume)

### ISSUE THREAD

**Issue by mchalunderscore** [crystal-linux/jade#11]
**Describe the bug**
Installation does not continue past grub target as it fails to run the necessary commands

**To Reproduce**
1. Boot an ISO built with the `crystal` profile in `iso/development`
2. Go through installation as normal, launching `jade-gui` through a terminal to see console output

**Expected behavior**
jade-gui continues installation process

**Screenshots**
### Installation Error
![image](https://user-images.githubusercontent.com/30374463/181859377-639138a2-c4f1-417d-96db-93455632ce82.png)

### /tmp/jade.json
![image](https://user-images.githubusercontent.com/30374463/181859454-32bf535f-4888-4c2a-b442-e69a12bbf257.png)

**Comment by axtloss** [comment]
Seems like an issue with jade, transferring the issue

**Comment by mchalunderscore** [comment]
What the fuck GitHub can do that?

**Comment by axtloss** [comment]
![image](https://user-images.githubusercontent.com/60044824/181908132-868699e5-e77a-4100-a3e8-838d1a05c1a8.png)

yeah lol

**Comment by axtloss** [comment]
fixed by commit [6604076](https://github.com/crystal-linux/jade/commit/660407638deef130ffa3a5399ba98a9aa1b0be83)

**Comment by axtloss** [comment]
i meant by commit https://github.com/crystal-linux/jade/commit/1ddef5e7a85c4e7608a8abf6e6cf4cfa893a81c3
