### ISSUE TITLE
[BUG]: /etc/localtime not being set

### ISSUE THREAD

**Issue by mchalunderscore** [crystal-linux/jade#37]
### Describe the bug

Users have reported /etc/localtime not being set on installed systems

### To reproduce the bug

1. Install
2. `file /etc/localtime`

### Expected behavior

`/etc/localtime` would be a symlink to the correct TZ

### Additional context

Reported by anti#0225 on Discord

**Comment by axtloss** [comment]
I'm not able to recreate the issue in any way, every crystal install which I have access to has the localtime file set right and when doing a fresh install it's also right

**Comment by mchalunderscore** [comment]
I'll close this for now, still potentially worthwhile investigating

**Comment by SomethingGeneric** [comment]
^ def worthwhile to follow up with, I wouldn't close it

**Comment by axtloss** [comment]
Oh that was already fixed in #39
